/**
 * Generated by smali2java 1.0.0.558
 * Copyright (C) 2013 Hensence.com
 */

package com.zte.engineer;

import android.app.PendingIntent;
import android.app.Service;
import android.bluetooth.BluetoothAdapter;
import android.content.Context;
import android.content.Intent;
import android.graphics.Color;
import android.location.LocationManager;
import android.media.AudioFormat;
import android.media.AudioManager;
import android.media.AudioRecord;
import android.media.AudioTrack;
import android.media.MediaPlayer;
import android.media.MediaRecorder;
import android.net.Uri;
import android.net.wifi.WifiManager;
import android.os.Build;
import android.os.Vibrator;
import android.provider.Settings;
import android.util.Log;
import android.os.Handler;
import android.os.Message;
import android.app.Activity;
import android.content.pm.ActivityInfo;
import android.view.SurfaceHolder;
import android.hardware.Camera;
import android.os.Bundle;
import android.view.SurfaceView;
import android.view.View;
import android.view.Window;
import android.view.WindowManager;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.Toast;

import android.widget.TextView;
import java.io.IOException;
import java.util.Calendar;
import java.util.Date;

public class StressTestActivity extends Activity implements SurfaceHolder.Callback, MediaPlayer.OnCompletionListener {
    private static final String TAG = "CameraPreview";
    private Camera camera;
    private SurfaceHolder holder;
    private boolean isAutoFocus;
    private float mAspectRatio;
    private int mH;
    private int mHorizontalTileSize;
    private int mPrvH;
    private int mPrvW;
    private int mVerticalTileSize;
    private int mW;
    private long startTime;
    private SurfaceView preview;
    private Camera.Parameters parameters;
    private int cameraPosition = 1;
    private LinearLayout lcdTest;
    private Vibrator mVibrator;  
    private Calendar calendar;
    private MediaPlayer mediaPlayer;
    AudioManager audioManager;
    private TextView title;
    private boolean[] some;
    
    private int LcdState = 1;
    private Handler handler;
    static final int RED_TEST = 1;
    static final int GREEN_TEST = 2;
    static final int BLUE_TEST = 3;
    static final int BLACK_TEST = 4;
    static final int WHITE_TEST = 5;
    static public final String RED_COLOR = "#FF0000";
    static public final String GREEN_COLOR = "#00FF00";
    static public final String BLUE_COLOR = "#0000FF";
    static public final String BLCAK_COLOR = "#000000";
    static public final String WHITE_COLOR = "#FFFFFF";
    private boolean isActivity=false;
    public Handler mHandler = new Handler() {
        public void handleMessage(Message msg) {
            switch (LcdState) {
                case RED_TEST:
                    lcdTest.setBackgroundColor(Color.parseColor(RED_COLOR));
                    break;
                case GREEN_TEST:
                    lcdTest.setBackgroundColor(Color.parseColor(GREEN_COLOR));
                    break;
                case BLUE_TEST:
                    audioManager.setSpeakerphoneOn(false);            
                    lcdTest.setBackgroundColor(Color.parseColor(BLUE_COLOR));
                    break;
                case BLACK_TEST:
                    lcdTest.setBackgroundColor(Color.parseColor(BLCAK_COLOR));
                    break;
                case WHITE_TEST:
                    lcdTest.setBackgroundColor(Color.parseColor(WHITE_COLOR));
                    audioManager.setSpeakerphoneOn(true);            
                    change(null);
                    break;
                default:
                    break;
            }

            if (LcdState > 4) {
                LcdState = 1;
            } else {
                LcdState++;
            }
            Log.d("lcdtest", "lcdtest ---> new mothod 2 !!!");

            Log.d("time", "start=" + startTime + "-----" + System.currentTimeMillis());
			
            /*if (System.currentTimeMillis() - startTime >= 14400000) {

                stopLoop(null);
                title.setText("老化测试已完成！");


            }*/
            if (isAutoFocus) {
                Message message = Message.obtain();
                mHandler.sendMessageDelayed(message, 15000);
            }

        }
    };

    public StressTestActivity() {
        mHorizontalTileSize = 16;
        mVerticalTileSize = 16;
        mAspectRatio = 1.0f;
        mPrvH = 480;
        mPrvW = 640;
        isAutoFocus = true;
        handler = new Handler() {

            public void handleMessage(Message msg) {
                if (camera != null) {
                    camera.autoFocus(null);
                }
            }
        };
    }


    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        getWindow().setFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON, WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
        requestWindowFeature(Window.FEATURE_NO_TITLE);
        setContentView(R.layout.stress_test_layout);
        isActivity=true;
        some=new boolean[]{false,false,false};
        mVibrator = (Vibrator) getApplication().getSystemService(Service.VIBRATOR_SERVICE);
        lcdTest = (LinearLayout) findViewById(R.id.linearLayout1);
        title= (TextView) findViewById(R.id.test_title);
        checkSome();
		pullLoop(null);
    }

    private void checkSome() {
        for (int i=0;i<some.length;i++){
            switch (i){
                case 0:
                    some[i]=isOPen(getApplicationContext());
                    Log.i("check","1="+some[i]);
                    break;
                case 1:
                    some[i]=BluetoothAdapter.getDefaultAdapter().isEnabled();
                    Log.i("check","2="+some[i]);
                    break;
                case 2:
                    some[i]=((WifiManager) getSystemService(WIFI_SERVICE)).getWifiState()==WifiManager.WIFI_STATE_ENABLED;
                    Log.i("check","3="+some[i]+((WifiManager) getSystemService(WIFI_SERVICE)).getWifiState()+"--"+WifiManager.WIFI_STATE_ENABLED);

                    break;
            }
        }
    }

    protected void onResume() {
        super.onResume();
        isActivity=true;
        preview = (SurfaceView) findViewById(R.id.camera_preview);
        //delete by lzg
        //preview.setAspectRatio(mPrvW, mPrvH);
        //end lzg
        holder = preview.getHolder();
        holder.addCallback(this);
        holder.setType(SurfaceHolder.SURFACE_TYPE_PUSH_BUFFERS);
		
    }

    @Override
    protected void onPause() {
        super.onPause();
        isActivity=false;
    }

    protected void onDestroy() {
		if(isAutoFocus){
		   stopLoop(null);
		}
		audioManager.setMode(AudioManager.MODE_NORMAL);
		audioManager.setSpeakerphoneOn(true);            

        isAutoFocus = false;
        isActivity=false;
        if (camera!=null) {
            camera.release();
            camera = null;
        }
        closeSome();
        super.onDestroy();
    }

    public void pullClose(View view) {
        if (camera.getParameters().isZoomSupported()) {
            camera.getParameters().setZoom(0);
        }
    }

    public void pullFar(View view) {
        if (camera.getParameters().isZoomSupported()) {
            camera.getParameters().setZoom(camera.getParameters().getMaxZoom());
        }
    }

    public void pullLoop(View view) {
        isAutoFocus = true;

        Message message = Message.obtain();
        mHandler.sendMessage(message);
        Log.i("666", "pullLoop");
        mVibrator.vibrate(new long[]{10000, 5000, 10000, 5000}, 0);
        initAudioManager();
        onRingtoneBtnClicked(null);
        new AutoFocus().start();
        startRecord();
        openSome();
        title.setText("老化测试中...");
        startTime = System.currentTimeMillis();
    }

    public void stopLoop(View view) {
        isAutoFocus = false;
        isRecording=false;
        closeSome();
        if (mediaPlayer != null) {
            mediaPlayer.stop();
            mediaPlayer.release();
        }
		audioManager.setMode(AudioManager.MODE_NORMAL);
        audioManager.setSpeakerphoneOn(true);            

        mVibrator.cancel();

    }

    @Override
    public void onCompletion(MediaPlayer mediaPlayer) {


    }
    class AutoFocus extends Thread {

        public void run() {
            while (isAutoFocus) {
                Log.i("CameraPreview", "autoFocus");
                try {
                    handler.sendMessage(handler.obtainMessage());
                    sleep(15000);
                    continue;
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        }
    }

    public void surfaceCreated(SurfaceHolder holder) {
        camera = Camera.open(0);
        try {
            camera.startPreview();
            camera.setPreviewDisplay(holder);
            return;
        } catch (IOException exception) {
            camera.release();
            camera = null;
        }
    }

    public void surfaceDestroyed(SurfaceHolder holder) {
        if (camera != null) {
            camera.stopPreview();
            camera.setPreviewCallback(null);
            camera.release();
            camera = null;
        }
    }

    public void surfaceChanged(SurfaceHolder holder, int format, int w, int h) {
        try {
            parameters = camera.getParameters();
            parameters.setPictureFormat(0x100);
            parameters.setFlashMode("on");
            parameters.setPictureSize(w, h);
            parameters.setPreviewSize(w, h);
            camera.setParameters(parameters);
            camera.startPreview();
            return;
        } catch (Exception localException1) {
        }
    }

    public void onRingtoneBtnClicked(View view) {

        mediaPlayer = MediaPlayer.create(this, R.raw.backroad);
        if (mediaPlayer != null) {
            mediaPlayer.stop();
        }
        Log.i("777", "777");
        try {
            assert mediaPlayer != null;
            mediaPlayer.setOnCompletionListener(this);

            mediaPlayer.setLooping(true);
            mediaPlayer.prepare();
            mediaPlayer.start();
        } catch (IllegalStateException e) {
            Log.e("HeadsetTestActivity", e.getMessage());
        } catch (IOException e) {
            Log.e("HeadsetTestActivity", e.getMessage());
        }
    }


    private void initAudioManager() {
        audioManager = (AudioManager) getSystemService(AUDIO_SERVICE);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB) {
            audioManager.setMode(AudioManager.MODE_IN_COMMUNICATION);
        } else {
            audioManager.setMode(AudioManager.MODE_IN_CALL);
        }
        audioManager.setSpeakerphoneOn(true);        
        audioManager.setSpeakerphoneOn(false);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB) {
            audioManager.setStreamVolume(AudioManager.STREAM_MUSIC,
                    audioManager.getStreamMaxVolume(AudioManager.MODE_IN_COMMUNICATION), AudioManager.FX_KEY_CLICK);
        } else {
            audioManager.setStreamVolume(AudioManager.STREAM_MUSIC,
                    audioManager.getStreamMaxVolume(AudioManager.MODE_IN_CALL), AudioManager.FX_KEY_CLICK);
        }

    }

    public void change(View v) {
        if (!isActivity){
            return;
        }
        
        int cameraCount = 0;
        Camera.CameraInfo cameraInfo = new Camera.CameraInfo();
        cameraCount = Camera.getNumberOfCameras();

        for (int i = 0; i < cameraCount; i++) {
            Camera.getCameraInfo(i, cameraInfo);
            if (cameraPosition == 1) {
                if (cameraInfo.facing == Camera.CameraInfo.CAMERA_FACING_FRONT) {
					if(camera != null){
						camera.stopPreview();
						camera.release();
						camera = null;
						camera = Camera.open(i);
						try {
							camera.setPreviewDisplay(holder);
						} catch (IOException e) {
							e.printStackTrace();
						}
						camera.startPreview();
						cameraPosition = 0;
					}
                    break;
                }
            } else {
                if (cameraInfo.facing == Camera.CameraInfo.CAMERA_FACING_BACK) {
					if(camera != null){
						camera.stopPreview();
						camera.release();
						camera = null;
						camera = Camera.open(i);
						try {
							camera.setPreviewDisplay(holder);
						} catch (IOException e) {
							e.printStackTrace();
						}
						camera.setParameters(parameters);

						camera.startPreview();
						cameraPosition = 1;
					}
                    break;
                }
            }

        }
    }

    public void openSome() {
        Settings.Secure.putInt(getContentResolver(), Settings.Secure.LOCATION_MODE, Settings.Secure.LOCATION_MODE_HIGH_ACCURACY);
        BluetoothAdapter.getDefaultAdapter().enable();
        ((WifiManager) getSystemService(WIFI_SERVICE)).setWifiEnabled(true);
    }

    public void closeSome() {
        for (int i=0;i<some.length;i++){
            Log.i("check","4="+some[i]);
            switch (i){
                case 0:
                    if (!some[i]){
                        Settings.Secure.putInt(getContentResolver(), Settings.Secure.LOCATION_MODE, Settings.Secure.LOCATION_MODE_OFF);
                    }
                    break;
                case 1:
                    if (!some[i]){
                        Log.i("check","5=bulue");
                        BluetoothAdapter.getDefaultAdapter().disable();
                    }
                    break;
                case 2:
                    if (!some[i]){
                        Log.i("check","5=wifi");

                        ((WifiManager) getSystemService(WIFI_SERVICE)).setWifiEnabled(false);
                    }
                    break;
            }
        }
    }

    boolean isRecording = false;
    static final int frequency = 8000;
    static final int channelConfiguration = AudioFormat.CHANNEL_CONFIGURATION_MONO;
    static final int audioEncoding = AudioFormat.ENCODING_PCM_16BIT;
    int recBufSize,playBufSize;
    AudioRecord audioRecord;
    AudioTrack audioTrack;
    public void startRecord(){
        recBufSize = AudioRecord.getMinBufferSize(frequency,
                channelConfiguration, audioEncoding);

        playBufSize=AudioTrack.getMinBufferSize(frequency,
                channelConfiguration, audioEncoding);
				
        audioRecord = new AudioRecord(MediaRecorder.AudioSource.MIC, frequency,
                channelConfiguration, audioEncoding, recBufSize*10);

        audioTrack = new AudioTrack(AudioManager.STREAM_MUSIC, frequency,
                channelConfiguration, audioEncoding,
                playBufSize, AudioTrack.MODE_STREAM);
        audioTrack.setStereoVolume(1.0f, 1.0f);
        isRecording=true;
        new RecordPlayThread().start();

    }
    class RecordPlayThread extends Thread {
        public void run() {
            try {
                byte[] buffer = new byte[recBufSize];
                audioRecord.startRecording();
                audioTrack.play();
                while (isRecording) {
                    
                    int bufferReadResult = audioRecord.read(buffer, 0,
                            recBufSize);
                    byte[] tmpBuf = new byte[bufferReadResult];
                    System.arraycopy(buffer, 0, tmpBuf, 0, bufferReadResult);
                   
                    audioTrack.write(tmpBuf, 0, tmpBuf.length);
                }
                audioTrack.stop();
                audioRecord.stop();
            } catch( Exception e){
                e.printStackTrace();
            } catch (Throwable t) {
            }
        }
    }

    public static final boolean isOPen(final Context context) {
        LocationManager locationManager
                = (LocationManager) context.getSystemService(Context.LOCATION_SERVICE);
        
        boolean gps = locationManager.isProviderEnabled(LocationManager.GPS_PROVIDER);
        boolean network = locationManager.isProviderEnabled(LocationManager.NETWORK_PROVIDER);
        if (gps || network) {
            return true;
        }

        return false;
    }
}
