


/*******************************************************************************
 *
 * Filename:
 * ---------
 *   gpio_jni.h
 *
 * Project:
 * --------
 *   Android
 *
 * Description:
 * ------------
 *    header file of gpio jni function
 *
 * Author:
 * -------
 *   Alextao
 *
 *******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>


#ifndef _Included_com_mediatek_engineermode_jnix
#define _Included_com_mediatek_engineermode_jnix
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     alextao_newmobi_com_gpiodemo_GPIO
 * Method:    GPIO_Init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_alextao_newmobi_com_gpiodemo_GPIO_gpioInit
  (JNIEnv *, jobject);

/*
 * Class:     alextao_newmobi_com_gpiodemo_GPIO
 * Method:    GPIO_UnInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_alextao_newmobi_com_gpiodemo_GPIO_gpioUnInit
  (JNIEnv *, jobject);

/*
 * Class:     alextao_newmobi_com_gpiodemo_GPIO
 * Method:    Get_gpio_max_number
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_alextao_newmobi_com_gpiodemo_GPIO_getGpioMaxNumber
  (JNIEnv *, jobject);

/*
 * Class:     alextao_newmobi_com_gpiodemo_GPIO
 * Method:    Set_gpio_input
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_alextao_newmobi_com_gpiodemo_GPIO_setGpioInput
  (JNIEnv *, jobject, jint);

/*
 * Class:     alextao_newmobi_com_gpiodemo_GPIO
 * Method:    Set_gpio_output
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_alextao_newmobi_com_gpiodemo_GPIO_setGpioOutput
  (JNIEnv *, jobject, jint);

/*
 * Class:     alextao_newmobi_com_gpiodemo_GPIO
 * Method:    Set_gpio_data_high
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_alextao_newmobi_com_gpiodemo_GPIO_setGpioDataHigh
  (JNIEnv *, jobject, jint);

/*
 * Class:     alextao_newmobi_com_gpiodemo_GPIO
 * Method:    Set_gpio_data_low
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_alextao_newmobi_com_gpiodemo_GPIO_setGpioDataLow
  (JNIEnv *, jobject, jint);


#ifdef __cplusplus
}
#endif
#endif






